stages:
  - stage : Snapshot
    jobs:
    - job: SnapshotJob 
      displayName: Snapshot Application
      workspace:
       clean: all
      steps:
        - checkout: self
          persistCredentials: true
        - bash: |
            pwd
          displayName: 'Action Test'
