- uses: Azure/pipelines@v1
  with:
    azure-devops-project-url: 'https://dev.azure.com/shunmw/shunmw'
    azure-pipeline-name: 'MS.desktopJS' # name of the Azure pipeline to be triggered
    azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
